/* 离线中英术语词典（面向前端/IT 需求文档场景手工整理）。
 * 格式：每行 `中文=英文1,英文2,...`（第一个为命名首选词）。
 * 以 # 开头为注释行。离线纯数据，可按团队需要增补。 */
window.DK_DICT_RAW = `
# ===== 页面与布局 =====
页面=page
页面布局=page layout
首页=home,index
主页=home
详情页=detail page
列表页=list page
落地页=landing page
活动页=campaign page
个人中心=profile center
工作台=workspace,dashboard
仪表盘=dashboard
控制台=console
后台=admin,backend
前台=frontend
导航=nav,navigation
导航栏=navbar
侧边栏=sidebar
顶栏=header,header bar
底部=footer
面包屑=breadcrumb
标签页=tab
选项卡=tab
轮播=carousel,swiper
轮播图=carousel,banner
瀑布流=waterfall,masonry
栅格=grid
容器=container
盒子=box
卡片=card
面板=panel
弹窗=modal,dialog
对话框=dialog
气泡=bubble,tooltip
提示=tip,toast
轻提示=toast
消息=message,notification
通知=notification
下拉菜单=dropdown
菜单=menu
菜单项=menu item
抽屉=drawer
锚点=anchor
占位=placeholder
骨架屏=skeleton,skeleton screen
加载中=loading
加载=load,loading
进度条=progress,progress bar
步骤条=steps
分页=pagination,pager
空状态=empty,empty state
滚动=scroll
懒加载=lazy load
无限滚动=infinite scroll
回到顶部=back to top,scroll to top
吸顶=sticky,sticky header
浮层=overlay,popup layer
遮罩=mask,overlay
全屏=fullscreen
响应式=responsive
断点=breakpoint
主题=theme
暗黑模式=dark mode
深色模式=dark mode
亮色模式=light mode
水印=watermark
图标=icon
Logo=logo
图片=image,picture,img
头像=avatar
封面=cover,poster
背景图=background image
视频=video
音频=audio
动效=animation
过渡=transition
动画=animation

# ===== 组件与表单 =====
组件=component
模块=module
区块=section,block
元素=element
节点=node
子组件=child component
父组件=parent component
表单=form
表单项=form item
输入框=input,text input
文本框=textbox
文本域=textarea
多行输入=textarea
富文本=rich text,richtext
富文本编辑器=rich text editor
编辑器=editor
代码编辑器=code editor
下拉框=select
下拉选择=select,dropdown
单选=radio
单选框=radio
复选=checkbox
复选框=checkbox
多选=multi select,checkbox
开关=switch
滑块=slider
日期选择器=date picker
时间选择器=time picker
日期范围=date range
日历=calendar
级联选择=cascader,cascade select
穿梭框=transfer
上传=upload
下载=download
附件=attachment
文件=file
文件上传=file upload
图片上传=image upload
拖拽上传=drag upload
拖拽=drag,drag and drop
排序=sort
拖拽排序=drag sort
标签=label,tag
徽标=badge
按钮=button,btn
主按钮=primary button
次按钮=secondary button
链接=link
超链接=hyperlink,link
文字提示=tooltip
表单校验=form validation
校验=validate,validation
验证=verify,validation
必填=required
选填=optional
错误提示=error message,error tip
错误=error
警告=warning
成功=success
失败=fail,failure

# ===== 数据与业务 =====
数据=data
数据源=data source
数据结构=data structure
数据类型=data type
字段=field
属性=property,attr
键=key
值=value
键值对=key-value pair
键名=key name
索引=index
主键=primary key
默认值=default value
默认=default
空值=null,nil
未定义=undefined
空字符串=empty string
布尔=boolean
字符串=string
数字=number
整数=integer,int
小数=decimal,float
浮点数=float
数组=array
对象=object
集合=set
映射=map
字典=dictionary,dict
元组=tuple
枚举=enum
常量=constant,const
变量=variable,var
参数=param,parameter
入参=input param
出参=output param
返回值=return value
返回=return
回调=callback
异步=async,asynchronous
同步=sync,synchronous
 promise=promise
队列=queue
栈=stack
链表=linked list
树=tree
哈希=hash
序列化=serialize
反序列化=deserialize
解析=parse
格式化=format
转义=escape
编码=encode
解码=decode
加密=encrypt
解密=decrypt
脱敏=mask,desensitize
过滤=filter
筛选=filter,screen
搜索=search
查询=query,search
查找=find,lookup
搜索框=search input
高级搜索=advanced search
模糊搜索=fuzzy search
搜索历史=search history
热搜=hot search
推荐=recommend
排序方式=sort type
升序=ascending,asc
降序=descending,desc
正序=ascending,asc
倒序=descending,desc
分页大小=page size
页码=page number,page no
总页数=total pages
总数=total,count
条数=count

# ===== 列表与操作 =====
列表=list
表格=table
数据表格=data table
单元格=cell
表头=table header
表尾=table footer
行=row
列=column
固定列=fixed column
固定表头=fixed header
合并单元格=merge cells
展开=expand
折叠=collapse
收起=collapse
展开收起=expand collapse
多选=multi select
全选=select all
反选=invert selection
勾选=check,check on
取消勾选=uncheck
选中=selected,checked
批量操作=batch operation
批量删除=batch delete
批量导入=batch import
批量导出=batch export
导入=import
导出=export
新增=add,create
添加=add,append
新建=create,new
创建=create
删除=delete,remove
移除=remove
清空=clear,empty
编辑=edit
修改=update,modify
更新=update
保存=save
提交=submit
确认=confirm
确定=confirm
取消=cancel
关闭=close
重置=reset
刷新=refresh,reload
重新加载=reload
预览=preview
复制=copy
粘贴=paste
剪切=cut
撤销=undo
重做=redo
上一步=previous step
下一步=next step
完成=done,complete
应用=apply
启用=enable
禁用=disable
开启=turn on,enable
关闭功能=turn off,disable
显示=show,display
隐藏=hide
切换=toggle,switch
置顶=pin to top,top
上移=move up
下移=move down
拖动=drag
点击=click,tap
双击=double click
长按=long press
滑动=swipe,slide
悬停=hover
聚焦=focus
失焦=blur
回车=enter
键盘=key,keyboard
快捷键=shortcut,hotkey
复制链接=copy link
分享=share
点赞=like
收藏=favorite,collect
关注=follow
评论=comment
回复=reply
举报=report
反馈=feedback
评价=review,rate
评分=rating,score
投票=vote
签到=check in,sign in
打卡=clock in,check in

# ===== 账号与权限 =====
用户=user
会员=member,vip
访客=guest,visitor
游客=guest
管理员=admin,administrator
超级管理员=super admin
运营=operation
角色=role
权限=permission,auth
权限组=permission group
菜单权限=menu permission
数据权限=data permission
账号=account
账户=account
用户名=username
昵称=nickname
密码=password
确认密码=confirm password
旧密码=old password
新密码=new password
手机号=phone,mobile
邮箱=email
验证码=captcha,verification code
短信验证码=sms code
图形验证码=image captcha
登录=login,sign in
登出=logout,sign out
退出登录=logout
注册=register,sign up
登录态=login state,auth state
单点登录=sso,single sign on
记住我=remember me
忘记密码=forgot password
找回密码=reset password
修改密码=change password
绑定=bind
解绑=unbind
授权=authorize,authorization
认证=authentication,auth
鉴权=authentication
令牌=token
会话=session
过期=expire,expired
失效=invalid,expired
个人信息=profile,personal info
头像上传=avatar upload
实名认证=real name verification
安全设置=security settings
隐私=privacy
协议=agreement
隐私政策=privacy policy
用户协议=user agreement
租户=tenant
组织=organization,org
部门=department,dept
团队=team

# ===== 电商与订单 =====
商品=product,goods
商品详情=product detail
商品列表=product list
分类=category
类目=category
标签库=tag library
品牌=brand
规格=spec,specification
库存=stock,inventory
价格=price
原价=original price
现价=current price
折扣=discount
优惠=promotion,discount
优惠券=coupon
红包=red packet,cash coupon
积分=points,credit
购物车=cart
加入购物车=add to cart
结算=settlement,checkout
下单=place order
订单=order
订单列表=order list
订单详情=order detail
订单状态=order status
支付=pay,payment
支付方式=payment method
付款=payment
收款=receive payment
退款=refund
退款申请=refund request
售后=after sales
退货=return goods
换货=exchange
发货=deliver,shipment
物流=logistics
快递=express,courier
运费=freight,shipping fee
包邮=free shipping
收货地址=shipping address
地址=address
收货人=consignee
签收=sign for,receipt
评价晒单=review with photos
库存不足=out of stock
售罄=sold out
上架=put on shelf,online
下架=take off shelf,offline
库存预警=stock alert
秒杀=seckill,flash sale
拼团=group buy
砍价=bargain
满减=full reduction
分销=distribution
佣金=commission

# ===== 系统与工程 =====
系统=system
平台=platform
服务=service
接口=api,interface
接口文档=api doc
请求=request
响应=response
请求头=headers
请求体=body,request body
响应体=response body
状态码=status code
超时=timeout
重试=retry
轮询=polling
长连接=long connection,websocket
心跳=heartbeat
网络=network
弱网=weak network
离线=offline
在线=online
版本=version
版本号=version number
迭代=iteration
需求=requirement,demand
需求文档=prd,requirement doc
原型=prototype
设计稿=design draft,mockup
切图=slice,assets
标注=annotation,spec
还原=restore,implement faithfully
联调=joint debugging,integration
提测=submit for testing
验收=acceptance
上线=release,go live
发布=release,publish
部署=deploy,deployment
构建=build
打包=package,build
编译=compile
热更新=hot update
灰度发布=gray release,canary release
回滚=rollback
环境=environment
开发环境=dev environment
测试环境=test environment
预发环境=staging environment
生产环境=production environment
配置=config,configuration
配置项=config item
环境变量=env,environment variable
域名=domain
内网=intranet
外网=external network
代理=proxy
跨域=cors,cross origin
白名单=whitelist
黑名单=blacklist
防火墙=firewall
网关=gateway
负载均衡=load balance
微服务=microservice
中间件=middleware
数据库=database,db
缓存=cache
缓存策略=cache strategy
本地缓存=local cache
会话存储=session storage
存储=storage
持久化=persistence
消息队列=message queue,mq
定时任务=scheduled job,cron job
任务=task,job
日志=log
埋点=tracking,event tracking
监控=monitor,monitoring
报警=alert,alarm
性能=performance
性能优化=performance optimization
首屏=first screen,first paint
白屏=white screen
卡顿=jank,lag
内存=memory
内存泄漏=memory leak
崩溃=crash
兼容性=compatibility
安全=security
漏洞=vulnerability
注入=inject,injection
攻击=attack
签名=signature
证书=certificate
协议=protocol
文档=document,doc
示例=example,demo
样例=sample
模板=template
脚手架=scaffold,boilerplate
组件库=component library
工具库=utility library
依赖=dependency
插件=plugin
扩展=extension
第三方=third party
开源=open source
仓库=repository,repo
分支=branch
合并请求=pull request,merge request
代码评审=code review
提交代码=commit
冲突=conflict
标签=tag,label
里程碑=milestone
工单=ticket
缺陷=bug,defect
测试用例=test case
自动化测试=automated test
单元测试=unit test
覆盖率=coverage
冒烟测试=smoke test
回归测试=regression test

# ===== 状态与流程 =====
状态=status,state
流程=flow,process
流程图=flowchart
工作流=workflow
审批=approval
审核=review,audit
审批流=approval flow
待处理=pending
处理中=processing
已完成=completed,done
已取消=cancelled
已关闭=closed
已过期=expired
进行中=in progress,ongoing
未开始=not started
暂停=paused
已暂停=paused
继续=resume,continue
终止=terminated,abort
成功状态=success state
失败状态=failure state
异常=exception,error
正常=normal
异常状态=abnormal state
生效=active,effective
失效=invalid,expired
可见=visible
不可见=invisible
可见性=visibility
只读=readonly
可编辑=editable
可拖拽=draggable
可排序=sortable
活动状态=active
激活=activate
未激活=inactive

# ===== 时间相关 =====
时间=time
日期=date
时间戳=timestamp
时区=timezone
当前时间=current time,now
创建时间=created at,create time
更新时间=updated at,update time
开始时间=start time
结束时间=end time
截止时间=deadline,due time
有效期=validity period,expiry
过期时间=expire time,expiry
剩余时间=remaining time,countdown
倒计时=countdown
今天=today
明天=tomorrow
后天=day after tomorrow
昨天=yesterday
前天=day before yesterday
本周=this week
上周=last week
下周=next week
本月=this month
上月=last month
下月=next month
本季度=this quarter
上季度=last quarter
今年=this year
去年=last year
明年=next year
每天=daily,every day
每周=weekly,every week
每月=monthly,every month
每年=yearly,annually
工作日=weekday
周末=weekend
上午=am,morning
下午=pm,afternoon
晚上=evening,night
凌晨=early morning,midnight
实时=realtime
延时=delay,deferred
定时=scheduled,timed
秒=second,sec
分钟=minute,min
小时=hour
天=day
周=week
月=month
季度=quarter
年=year

# ===== 常用动词 =====
获取=get,fetch,acquire
得到=get
设置=set,set up
读取=read
写入=write
保存数据=save data
加载=load
渲染=render
挂载=mount
卸载=unmount
初始化=init,initialize
销毁=destroy
释放=release
监听=listen,observe
触发=trigger
派发=dispatch
订阅=subscribe
发布消息=publish
广播=broadcast
拦截=intercept
阻止=prevent
阻止默认=prevent default
冒泡=bubble,propagate
捕获=capture
遍历=traverse,iterate
映射转换=map
归并=reduce
拼接=concat,join
分割=split
截取=slice,substring
替换=replace
匹配=match
比较=compare
转换=convert,transform
计算=calculate,compute
求和=sum
平均值=average,avg
最大值=max
最小值=min
去重=deduplicate,unique
翻转=reverse
压缩=compress
解压=decompress
校验规则=validation rule
生成=generate
拷贝=clone,copy
合并=merge
覆盖=override
继承=inherit
实现=implement
定义=define
声明=declare
导出数据=export data
导入数据=import data
上传文件=upload file
下载文件=download file
打开=open
跳转=navigate,jump
重定向=redirect
路由=route,router
路由跳转=route navigation
返回上一页=go back
刷新页面=refresh page
滚动到=scroll to
定位=locate,position
居中=center
对齐=align

# ===== 常用名词（通用） =====
名字=name
名称=name,title
标题=title
副标题=subtitle
描述=description,desc
说明=description,note
备注=remark,note
内容=content
正文=body,content
摘要=summary,abstract
简介=intro,brief
详情=detail
信息=info,information
消息提醒=message notification
帮助=help
指南=guide
教程=tutorial,tutor
手册=manual,handbook
示例代码=sample code
演示=demo
用户手册=user manual
首页轮播=home carousel
公告=announcement,notice
公告栏=notice board
 banner=banner
广告=ad,advertisement
运营位=operation slot,ad slot
楼层=floor,section
栏目=column,channel
频道=channel
分类导航=category nav
热门=hot,popular
最新=newest,latest
最新消息=latest news
新闻=news
资讯=information,news
文章=article
帖子=post
动态=feed,moment
朋友圈=moments
私信=direct message,dm
聊天=chat
通讯录=contacts
好友=friend
群组=group
直播=live,livestream
回放=playback,replay
点赞数=like count
浏览量=view count,pv
访问量=traffic,pv
点击量=click count,ctr
转化率=conversion rate
留存=retention
活跃度=activity,engagement
日活跃=dau
月活跃=mau
统计=statistics,stats
报表=report
图表=chart
柱状图=bar chart
折线图=line chart
饼图=pie chart
雷达图=radar chart
散点图=scatter chart
热力图=heatmap
地图=map
图例=legend
坐标轴=axis
横轴=x axis
纵轴=y axis
数据大屏=data screen,big screen
可视化=visualization
大屏=big screen,dashboard

# ===== 需求文档高频补充 =====
自动=auto,automatic
手动=manual
发送=send
接收=receive
短信=sms,text message
通知=notify,notification
提醒=remind,reminder
之后=after
之前=before
回调函数=callback function
回调=callback
请求参数=request params
返回结果=result,response
失败原因=failure reason
错误信息=error message
提示信息=tip message
弹窗提示=popup tip
确认弹窗=confirm dialog
功能=function,feature
功能点=feature point
业务=business
业务逻辑=business logic
场景=scenario,scene
使用场景=use case
用户故事=user story
角色权限=role permission
数据字典=data dictionary
埋点上报=tracking report
异常处理=error handling
兜底=fallback
降级=degrade,degradation
容错=fault tolerance
幂等=idempotent
并发=concurrency
高并发=high concurrency
限流=rate limit,throttling
重试机制=retry mechanism
轮询间隔=polling interval
断线重连=reconnect
弱网优化=weak network optimization
兼容=compatible,compatibility
适配=adapt,adaptation
浏览器兼容=browser compatibility
移动端=mobile,mobile terminal
小程序=mini program
内嵌页面=embedded page,webview
混合开发=hybrid development
原生=native
前端页面=frontend page
静态页面=static page
动态页面=dynamic page
单页应用=spa,single page application
服务端渲染=ssr,server side rendering
预渲染=prerender
国际化=i18n,internationalization
多语言=multilingual,i18n
无障碍=accessibility,a11y
埋点管理=tracking management
灰度=gray,canary
体验优化=ux optimization
用户引导=user guide,onboarding
新手引导=onboarding guide
功能开关=feature toggle,feature flag
开关配置=toggle config
实验=experiment,ab test
ab测试=a/b test
白屏检测=white screen detection
错误上报=error report
性能监控=performance monitoring
数据埋点=data tracking
请求合并=request merge
接口 Mock=api mock
模拟数据=mock data
联调环境=integration environment
预览环境=preview environment
临时=temporary,temp
正式=official,production
测试数据=test data
脏数据=dirty data
增量=incremental
全量=full,full amount
同步更新=sync update
异步加载=async load
预加载=preload
预取=prefetch
分片=shard,chunk
断点续传=resumable upload
秒传=instant upload
文件预览=file preview
在线预览=online preview
导出报表=export report
打印=print
截图=screenshot
录制=record
回放功能=playback
消息推送=push notification
推送=push
订阅消息=subscribe message
模板消息=template message
广播通知=broadcast
未读数=unread count
红点=red dot,badge
角标=badge
下拉刷新=pull to refresh
上拉加载=load more
骨架=skeleton placeholder

# ===== 命名组合词（中文直接转变量名时高优先）=====
转=convert
转发=forward
中文=chinese
变量名=variable name
函数名=function name
方法名=method name
类名=class name
组件名=component name
属性名=property name
参数名=param name
目录名=directory name
字段名=field name
接口名=api name
变量名称=variable name
函数名称=function name
列表项=list item
表格列=table column
按钮组=button group
响应数据=response data
接口地址=api url
数据列表=data list
用户信息=user info
用户列表=user list
订单详情=order detail
订单编号=order no
商品列表=product list
商品编号=product no
搜索结果=search result
数据表格=data table
表单校验=form validation
页面标题=page title
页面地址=page url
主题色=theme color
弹窗标题=dialog title
侧边栏菜单=sidebar menu
顶部导航=top nav
底部导航=bottom nav
登录页面=login page
注册页面=register page
个人中心=profile center
消息列表=message list
通知列表=notification list
数据统计=data statistics
数据看板=data dashboard
操作日志=operation log
系统设置=system settings
权限管理=permission management
角色管理=role management
用户管理=user management
订单管理=order management
商品管理=product management

# ===== 结构词（值写 ~ 表示翻译时省略，让英文更通顺）=====
的=~
地=~
得=~
了=~
着=~
过=~
们=~
把=~
时=~
之=~
就=~
才=~
呢=~
吧=~
啊=~
哟=~
哦=~

# ===== 高频补充词 =====
后=~
前=~
帮=help
帮我=help me
帮忙=help
一下=~
一次=once
一句=sentence
句子=sentence
这句话=this sentence
那句话=that sentence
弹出=pop up
弹出来=pop up
浮出=pop up
出一个=output
出=out
次=time,times
看到=see,view
查看=view,check
展示=display,show
显示出来=show
服务器=server
里面=inside
上面=above
下面=below
前面=front
后面=back
左边=left
右边=right
中间=middle
旁边=beside
附近=nearby
以后=later
以前=before
现在=now,currently
刚才=just now
结束时间=end time
开始时间=start time
时间段=time range
日期范围=date range
天数=days
次数=count
个数=count
行数=row count
列数=column count
宽度=width
高度=height
距离=distance
位置=position,location
方向=direction
速度=speed
质量=quality
数量=quantity
种类=type,kind
部分=part
整体=whole
全部=all,entire
一半=half
两个=two
三个=three
第一个=first
最后一个=last
每个用户=each user
所有用户=all users
当前用户=current user
当前页面=current page
目标页面=target page
源页面=source page
上一个=previous
下一个=next
第一页=first page
最后一页=last page
升序排列=ascending order
降序排列=descending order
按时间排序=sort by time
按名称排序=sort by name
求和=sum up
求平均=calculate average
分组统计=group by
汇总=summary
明细=detail
差异=difference
对比=compare
比例=ratio
百分比=percentage
趋势=trend
波动=fluctuation
峰值=peak
平均值=average value
最大值=max value
最小值=min value

# ===== 常用词（提升整句翻译可读性，优先于扩充词典）=====
我=i
我们=we
你=you
你们=you
他=he
她=she
它=it
这个=this
那个=that
这些=these
那些=those
我的=my
你的=your
什么=what
怎么=how
为什么=why
哪里=where
谁=who
是不是=is it
吗=?
请=please
可以=can
需要=need
必须=must
不要=do not
无法=cannot
是否=whether
已经=already
马上=immediately
然后=then
但是=but
并且=and
同时=meanwhile
关于=about
用于=for
通过=through
根据=according to
例如=for example
包括=include
所有=all
每个=each
一些=some
很多=many
更多=more
没有=none
有=have
不是=is not
你好=hello
谢谢=thanks
帮助=help
支持=support
问题=issue
错误=error
版本=version
手机=phone,mobile
客户端=client
服务端=server
浏览器=browser
电脑=computer
键盘=keyboard
鼠标=mouse
屏幕=screen
分辨率=resolution
音乐=music
游戏=game
电话=phone
号码=number
代码=code
注释=comment
文件名=file name
目录=directory
路径=path
根目录=root directory
命令行=command line
终端=terminal
依赖包=dependency
打包工具=bundler
样式=style
主题色=theme color
字号=font size
行高=line height
间距=spacing
圆角=border radius
阴影=shadow
渐变=gradient
交互=interaction
手势=gesture
滚动条=scrollbar
输入法=input method
剪贴板=clipboard
二维码=qr code
扫码=scan
蓝牙=bluetooth
相机=camera
相册=album
麦克风=microphone
安装=install
修复=fix
排查=troubleshoot
复现=reproduce
优化=optimize
重构=refactor
抽取=extract
封装=encapsulate
抽象=abstract
调用=call
执行=execute
循环=loop
递归=recursion
异常捕获=catch exception
空指针=null pointer
边界=boundary
默认值=default value
超时时间=timeout
重试次数=retry count
并发数=concurrency
请求失败=request failed
响应超时=response timeout
数据为空=data is empty
加载失败=load failed
操作成功=operation succeeded
请稍等=please wait
确认删除=confirm delete
是否继续=continue
温馨提示=tip
暂无数据=no data
网络异常=network error
系统繁忙=system busy
重新登录=re-login
无权访问=no permission
页面不存在=page not found
服务不可用=service unavailable
请求过于频繁=too many requests
参数错误=invalid parameter
`;
